appName: adservice
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: "sha256:4780e3e9dacc787ebf1e338f2cb989823f92b2cf7ab9935d554bd9d0a687e444"
appReplicas: 1
containerPort: 9555
containerEnvVar:
  - name: PORT
    value: "9555"
  - name: GOOGLE_CLOUD_PROJECT
    value: "my-kubernetes-project"
  - name: DISABLE_TRACING
    value: "1"
  - name: DISABLE_PROFILER
    value: "1"
  - name: DISABLE_DEBUGGER
    value: "1"

serviceType: ClusterIP
servicePort: 9555
