appName: cartservice
appImage: gcr.io/google-samples/microservices-demo/cartservice
appVersion: "sha256:ed9a9a922e35ec3b8373155444bd65f182c9bd9ff81c89fc27eed4eda3987944"
appReplicas: 1
containerPort: 7070
containerEnvVar:
  - name: PORT
    value: "7070"
  - name: REDIS_ADDR
    value: "redis-cart:6379"
  - name: GOOGLE_CLOUD_PROJECT
    value: "my-kubernetes-project"
  - name: DISABLE_TRACING
    value: "1"
  - name: DISABLE_PROFILER
    value: "1"
  - name: DISABLE_DEBUGGER
    value: "1"

serviceType: ClusterIP
servicePort: 7070
