appName: checkoutservice
appImage: gcr.io/google-samples/microservices-demo/checkoutservice
appVersion: "sha256:c4233881c64ceb6daccf16c5b1d30fab6af85e94a2057fa3423baad6328ba13d"
appReplicas: 1
containerPort: 5050
containerEnvVar:
  - name: PORT
    value: "5050"
  - name: EMAIL_SERVICE_ADDR
    value: "emailservice:8080"
  - name: PAYMENT_SERVICE_ADDR
    value: "paymentservice:50051"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: CART_SERVICE_ADDR
    value: "cartservice:7070"
  - name: GOOGLE_CLOUD_PROJECT
    value: "my-kubernetes-project"
  - name: DISABLE_TRACING
    value: "1"
  - name: DISABLE_PROFILER
    value: "1"
  - name: DISABLE_DEBUGGER
    value: "1"
serviceType: ClusterIP
servicePort: 5050
