appName: paymentservice
appImage: gcr.io/google-samples/microservices-demo/paymentservice
appVersion: "sha256:64df556b6fb98e258e7e51f06ac0780564c34b021cc2749aa65b2eae6c9fd6ae"
appReplicas: 2
containerPort: 50051
containerEnvVar:
  - name: PORT
    value: "50051"
  - name: GOOGLE_CLOUD_PROJECT
    value: "false"
  - name: DISABLE_TRACING
    value: "1"
  - name: DISABLE_PROFILER
    value: "1"
  - name: DISABLE_DEBUGGER
    value: "1"

serviceType: ClusterIP
servicePort: 50051
