apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: default
  labels:
    app: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  replicas: 1
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: gcr.io/google-samples/microservices-demo/adservice@sha256:4780e3e9dacc787ebf1e338f2cb989823f92b2cf7ab9935d554bd9d0a687e444
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: PORT
              value: "9555"
            - name: GOOGLE_CLOUD_PROJECT
              value: "my-kubernetes-project"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_DEBUGGER
              value: "1"
          ports:
            - containerPort: 9555
              name: adservice
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: default
spec:
  selector:
    app: adservice
  type: ClusterIP
  ports:
    - name: adservice
      protocol: TCP
      port: 9555
      targetPort: 9555
