apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: default
  labels:
    app: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  replicas: 1
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: gcr.io/google-samples/microservices-demo/cartservice@sha256:ed9a9a922e35ec3b8373155444bd65f182c9bd9ff81c89fc27eed4eda3987944
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: PORT
              value: "7070"
            - name: REDIS_ADDR
              value: "redis-cart:6379"
            - name: GOOGLE_CLOUD_PROJECT
              value: "my-kubernetes-project"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_DEBUGGER
              value: "1"
          ports:
            - containerPort: 7070
              name: cartservice
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: default
spec:
  selector:
    app: cartservice
  type: ClusterIP
  ports:
    - name: cartservice
      protocol: TCP
      port: 7070
      targetPort: 7070
