apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: default
  labels:
    app: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  replicas: 1
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: currencyservice
          image: gcr.io/google-samples/microservices-demo/currencyservice@sha256:ebd95396ceb54635b825d0acc499ebe322ddf5caf31b42cf4261eb3d87eda5c2
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: PORT
              value: "7000"
            - name: GOOGLE_CLOUD_PROJECT
              value: "my-kubernetes-project"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_DEBUGGER
              value: "1"
          ports:
            - containerPort: 7000
              name: currencyservice
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: default
spec:
  selector:
    app: currencyservice
  type: ClusterIP
  ports:
    - name: currencyservice
      protocol: TCP
      port: 7000
      targetPort: 7000
