apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: default
  labels:
    app: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  replicas: 1
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice
          image: gcr.io/google-samples/microservices-demo/emailservice@sha256:86cfe447a4a12770fceb64b2157af9b203b4d99bc03ad27fb26628577cba51a1
          resources:
          env:
            - name: PORT
              value: "8080"
            - name: GOOGLE_CLOUD_PROJECT
              value: "my-kubernetes-project"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_DEBUGGER
              value: "1"
          ports:
            - containerPort: 8080
              name: emailservice
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: default
spec:
  selector:
    app: emailservice
  type: ClusterIP
  ports:
    - name: emailservice
      protocol: TCP
      port: 5000
      targetPort: 8080
