apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/google-samples/microservices-demo/frontend@sha256:65309ed5b172d4c9523b0101c0c31971e3a2f4109e38b0e0e87d0ee6e4948e6e
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendationservice:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkoutservice:5050"
            - name: AD_SERVICE_ADDR
              value: "adservice:5050"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: GOOGLE_CLOUD_PROJECT
              value: "my-kubernetes-project"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_DEBUGGER
              value: "1"

          ports:
            - containerPort: 8080
              name: frontend
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - name: frontend
      protocol: TCP
      port: 8080
      targetPort: 8080
