apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: default
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  replicas: 1
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: gcr.io/google-samples/microservices-demo/paymentservice@sha256:64df556b6fb98e258e7e51f06ac0780564c34b021cc2749aa65b2eae6c9fd6ae
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: PORT
              value: "50051"
            - name: GOOGLE_CLOUD_PROJECT
              value: "false"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_DEBUGGER
              value: "1"
          ports:
            - containerPort: 50051
              name: paymentservice
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: default
spec:
  selector:
    app: paymentservice
  type: ClusterIP
  ports:
    - name: paymentservice
      protocol: TCP
      port: 50051
      targetPort: 50051
