apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: default
  labels:
    app: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  replicas: 1
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: gcr.io/google-samples/microservices-demo/shippingservice@sha256:f56326de45e6feb26342100e2909510d66a8f22d9184cd16c9160de959416fbf
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: PORT
              value: "50051"
            - name: GOOGLE_CLOUD_PROJECT
              value: "my-kubernetes-project"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_DEBUGGER
              value: "1"
          ports:
            - containerPort: 50051
              name: shippingservice
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: default
spec:
  selector:
    app: shippingservice
  type: ClusterIP
  ports:
    - name: shippingservice
      protocol: TCP
      port: 50051
      targetPort: 50051
