apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }} 
  namespace: default
spec:
  selector:
    app: {{ .Values.appName }} 
  type: {{ .Values.serviceType }} 
  ports:
    - name: {{ .Values.appName }}
      protocol: TCP
      port: {{ .Values.servicePort }} 
      targetPort: {{ .Values.containerPort }} 