apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: default
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.appReplicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.appImage }}@{{ .Values.appVersion  }}"
          resources:
            limits:
              cpu: {{ .Values.cpu }}
              memory: {{ .Values.memory }}
          env:
          {{- range .Values.containerEnvVar}}
          - name: {{ .name }}
            value: {{ .value | quote }} 
          {{- end}}  

          ports:
            - containerPort: {{ .Values.containerPort }}
      restartPolicy: Always
